### ISSUE TITLE
Provisioning fails because of missing file(s)

### ISSUE THREAD

**Issue by hbokh** [varnish/varnish-microservice-monitor#11]
At least one file is missing: `.bashrc` that will result in Ansible aborting:

```
TASK: [Add author information] ************************************************
failed: [192.168.75.41] => {"failed": true}
msg: could not find src=/Users/foobar/develop/zipnish/provisioning/build/files/ubuntu-vivid64/.bashrc

FATAL: all hosts have already failed -- aborting
```

**Comment by adeelshahid** [comment]
I'll check this one and come back

**Comment by adeelshahid** [comment]
Hi Henk @hbokh,

Please try now. I have removed the line from provisioning. You can pull and try again.
If you are trying to build for a particular platform let me know.

For developing Zipnish you won't not need build-ubuntu-vivid64 to be up an running using ansible / vagrant.

Adeel

**Comment by hbokh** [comment]
Now it is waiting for `run dh-make` indefinitely:

```
PLAY [Build for ubuntu-vivid 15.x 64-bit] *************************************

GATHERING FACTS ***************************************************************
ok: [192.168.75.41]

TASK: [update apt-cache] ******************************************************
ok: [192.168.75.41]

TASK: [install requirements for building debian package] **********************
changed: [192.168.75.41] => (item=gnupg,packaging-dev,pbuilder,debootstrap,ubuntu-dev-tools,bzr-builddeb,apt-file,build-essential,devscripts,debhelper,dh-make,bzr-builddeb)

TASK: [make zipkin-ui tar.gz] *************************************************
changed: [192.168.75.41]

TASK: [run dh-make] ***********************************************************
```

Maybe re-run the whole provisioning yourself too?
To speed things up I added this to the Vagrantfile, using plugins `vagrant-cachier` and `vagrant-vbguest`:

```
    config.vbguest.no_install = true

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.synced_folder_opts = {
          type: :nfs,
          mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
        }
        end
```

**Comment by adeelshahid** [comment]
I have removed the build.yml file from main provisioning

It's stuck there because user input is needed and Ansible 2.0 has that feature.

For now If you want build a ubuntu package you can checkout the document here https://github.com/varnish/zipnish/tree/master/packaging/ubuntu-vivid64

**Comment by adeelshahid** [comment]
you can fork and push changes, i'll merge
