### ISSUE TITLE
Can't setup the demo

### ISSUE THREAD

**Issue by aondio** [varnish/varnish-microservice-monitor#14]
output from "vagrant up":
`There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/vagrant/zipnish/Vagrantfile:8: syntax error, unexpected ':', expecting kEND
        userinterface.vm.network :private_network, ip: '192.168.75.11'
                                                      ^
/home/vagrant/zipnish/Vagrantfile:14: syntax error, unexpected ':', expecting kEND
        database.vm.network :private_network, ip: '192.168.75.12'
                                                 ^
/home/vagrant/zipnish/Vagrantfile:20: syntax error, unexpected ':', expecting kEND
        backend.vm.network :private_network, ip: '192.168.75.13'
                                                ^
/home/vagrant/zipnish/Vagrantfile:26: syntax error, unexpected ':', expecting kEND
        exampleapp.vm.network :private_network, ip: '192.168.75.14'
                                                   ^
/home/vagrant/zipnish/Vagrantfile:35: syntax error, unexpected ':', expecting kEND
        ubuntu.vm.network :private_network, ip: '192.168.75.41'
`

virtualbox version: Oracle VM VirtualBox Manager 4.1.44_Ubuntu
vagrant version: Vagrant version 1.0.1
Os: Ubuntu 12.04.5 LTS

**Comment by marme660** [comment]
yes, I could not also make it run the other day.

**Comment by mariusmagureanu** [comment]
I'll have a look at it.

**Comment by hugocruz** [comment]
I was able to run it with Vagrant 1.8.1 and Virtualbox 5.0.4. No errors in the file. Probably upgrading Vagrant will fix it. This file is using the new syntax.

**Comment by aondio** [comment]
ok, let me fix it and try again ;)
