### ISSUE TITLE
Use of DNS Names in Host Headers

### ISSUE THREAD

**Issue by enmatt** [varnish/varnish-microservice-monitor#17]
If you use anything other than an IP address when making calls you'll recieve the following error:

> 2016-04-22 14:34:50,150 ERROR: invalid literal for int() with base 10: 'apis' [in /opt/zipnish/log-reader/app.py:109]

Could logging be set to use the x-forward-for header as the source of the request, or for server.ip be used in place of the host header?

**Comment by mariusmagureanu** [comment]
The ip handling issue has been addressed, currently it's only in a dev branch. There are a few other things in the queue for the dev branch, after which I'll have them merged into master.

I'll keep you posted with this one, I'd be interested in your input with a few other various things.
