### ISSUE TITLE
Status of zipnish

### ISSUE THREAD

**Issue by ronaldploeger** [varnish/varnish-microservice-monitor#20]
The last commit on zipnish was more than half a year ago. Can anyone comment on the status of this project? Is it still alive already dead - which would be a pity. 

Thanks,
Ronald

**Comment by mariusmagureanu** [comment]
@ronaldploeger The project is not dead, however, lately it has not been that active, that's true.
In the short run we'll need to test it against the latest Varnish 5.0

If you have any suggestions/ideas here - I'd be more then happy to pick them up.

**Comment by ronaldploeger** [comment]
Thanks, 

this is great to hear. I think this is a very interesting project and would like to take a deeper look into it next year. 

In your opinion: Is this production ready? You do not have any releases / tags. Do you consider creating releases for the different varnish versions?

Thanks,
Ronald

**Comment by mariusmagureanu** [comment]
Hi Ronald,

No, as is today - it is not production ready, it does require a bit more thorough testing, in terms of how it would actually perform in practice.

Irw varnish version I'm not sure I'll have specific versions to match the given varnish instance. I'd rather have this configurable and make Zipnish adapt itself to any version. At the end of the day it's all about the varnish bindings.

Would you be interested in giving it a spin at some point?

//Marius

**Comment by ronaldploeger** [comment]
Hi Marius, 

as mentioned I would definitely like to take a closer look and try it out later this year. But this only makes sense to me if there is any progress / activity in the project. 

Best,
Ronald

**Comment by mariusmagureanu** [comment]
Hi Ronald,

 The projects still has lots of todo's in its pipeline. Starting early this spring it will receive more attention. However, what it lacks most is some external input, so if you're willing to pitch in with any ideas that would be highly appreciated.

 On a side note, there is a rough version of the ```logreader``` component started to be written in Go.

//Marius

**Comment by ronaldploeger** [comment]
Hi Marius, 

I am certainly willing to give you an outside perspective once we start evaluating this. I will contact you via email then. 

Best,
Ronald
